import Footer from '@/components/modules/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Header from '@/components/modules/Header'
import SessionProvider from '@/components/modules/SessionProvider'
import { getServerSession } from 'next-auth'
import authOptions from '@/config/authOptions'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)
  
  return (
    <html lang="en">
      <body className={nunito.className}>
        <SessionProvider session={session}>
          <Header />
          <main >
            {children}
          </main>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  )
}
