import Footer from '@/components/modules/Footer'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Header from '@/components/modules/Header'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        <main >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
